# 按照最新的语言语法，完善这个githubaction编译脚本
name: Build Multi-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build clipboard_app (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --name=clipboard_app --add-data "templates;templates" --add-data "static;static" app.py -y
        pyinstaller --name=apploader apploader.py -y
    
    - name: Build clipboard_app (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller --name=clipboard_app --add-data "templates:templates" --add-data "static:static" app.py -y
        pyinstaller --name=apploader apploader.py -y
    
    - name: Upload clipboard_app artifact
      uses: actions/upload-artifact@v3
      with:
        name: clipboard_app-${{ matrix.os }}
        path: dist/clipboard_app*
    
    - name: Upload apploader artifact
      uses: actions/upload-artifact@v3
      with:
        name: apploader-${{ matrix.os }}
        path: dist/apploader*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          clipboard_app-*/clipboard_app*
          apploader-*/apploader*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  