# 按照最新的语言语法，完善这个githubaction编译脚本
name: Build Multi-Platform

on:
  workflow_dispatch:
jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          clipboard_app-*/clipboard_app*
          apploader-*/apploader*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  